In [1]:
import pandas as pd

In [14]:
header = ['ind','created_at','member_id','text','textLength','source','user','verified','screen_name','verified_type','user_description','bid','longText']

In [37]:
applecn_df=pd.read_csv("weibo_%23%E8%8B%B9%E6%9E%9C%23_scrap_fullstr.csv",encoding = "gb18030",names=header,index_col=0)

In [36]:
applecn_df.head()

,ind,created_at,member_id,text,textLength,source,user,verified,screen_name,verified_type,user_description,bid,longText
0,0,2020-03-02 00:18:31,4478060432359830,震惊！！ 开天辟地之作， #苹果# 慌了， #雷军# 傻眼了，张老板坐不住了， #黄章# 也...,140,鸿蒙OS&Android,"{'id': 1967280501, 'screen_name': '科技小天', 'pro...",True,科技小天,0,私信看到都会回！感谢关注 ！！爱你们！！！,IwKHV9TTM,NaN
1,1,2020-02-28 20:18:31,4477057352854267,库克的苹果仍创新。 #苹果# #乔布斯# DannyData小丹尼的微博视频,55,财经 · 视频社区,"{'id': 2679375953, 'screen_name': 'DannyData小丹...",True,DannyData小丹尼,0,dannydata.com,IwkC3bYwz,NaN
2,2,2020-03-02 12:18:31,4478235738328329,#苹果# 年度股东大会召开，库克称疫情仍是挑战，要保持警惕！ 科技君的眼镜的微博视频,77,微博网页,"{'id': 6086153006, 'screen_name': '科技君的眼镜', 'p...",True,科技君的眼镜,0,科学实验视频,IwPgFyWzT,NaN
3,3,2020-03-02 05:18:31,4478125188450007,再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...,583,NaN,"{'id': 7258446663, 'screen_name': '互联网八哥', 'pr...",True,互联网八哥,0,每日一扒，看不一样的互联网,IwMomzser,再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...
4,4,2020-03-02 01:18:31,4478064711058365,近日，苹果在日本发布了全新的动画广告视频，在各种动漫场景中展示了MacBook和AirPod...,248,微博 weibo.com,"{'id': 7382535180, 'screen_name': '潮玩生活_张大喵', ...",False,潮玩生活_张大喵,-1,美妆、球鞋、数码、潮流好物这里都有～我是《潮玩生活》小编--张大喵。,IwKOP4rkp,NaN

In [78]:
appleen_df=pd.read_csv("weibo_Apple_scrap_fullstr.csv",encoding = "gb18030",index_col=0)

In [42]:
appleen_df.head()

,created_at,member_id,text,textLength,source,user,verified,screen_name,verified_type,user_description,longText,bid
0.0,2020-03-01 03:42:50,4477738171840551,想找星空图但是没找到称心的？ 那就自己画吧~ 用Procreate可以三秒做一张！ 【工具】...,359,ppt365超话,"{'id': 1774015623, 'screen_name': '嘉文钱', 'prof...",True,嘉文钱,0,PPT设计师，平面设计师，业余插画师，可以接稿,想找星空图但是没找到称心的？\n那就自己画吧~\n用Procreate可以三秒做一张！\n\...,IwCk97IOj
1.0,2020-03-01 23:15:50,4478048000469140,【日本 Apple 全新 MacBook 广告集结著名动画场景】早前 Apple 日本推出全...,302,微博 weibo.com,"{'id': 2067301197, 'screen_name': 'HYPEBEAST時尚...",True,HYPEBEAST時尚生活雜誌,3,HYPEBEAST 官方微博。 微信: hypebeastchina， 网站：http://...,【日本 Apple 全新 MacBook 广告集结著名动画场景】早前 Apple 日本推出全...,IwKnS1Y2M
2.0,2020-03-01 21:42:50,4478024323998938,【来看看动画中的“水果电脑”】Apple Japan于近日公开了一支全新的广告，其中Appl...,308,微博 weibo.com,"{'id': 1998412373, 'screen_name': '机核网', 'prof...",True,机核网,2,不止是游戏,【来看看动画中的“水果电脑”】Apple Japan于近日公开了一支全新的广告，其中Appl...,IwJLGgMj0
3.0,2020-03-01 23:31:50,4478052039974125,我一直不敢讲 虽然我坚持用Apple Music白嫖bts歌两年多了 但是我人脸依然只认识n...,215,iPhone客户端,"{'id': 5855864588, 'screen_name': 'IsKayo', 'p...",False,IsKayo,-1,总有一个终点，花开满树是人间💮,NaN,IwKunFQIZ
4.0,2020-03-01 23:30:50,4478051947881706,#iPhone样机# 设计君每日欣赏超话 多角度苹果iPhone Xs手机样机Apple X...,98,微博 weibo.com,"{'id': 3243464264, 'screen_name': 'UI设计君', 'pr...",True,UI设计君,0,NaN,NaN,IwKuex4oi

In [39]:
applecn_filtered = applecn_df.drop(columns=["verified","source","longText"])
applecn_filtered.head()

,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
ind,,,,,,,,,
0,2020-03-02 00:18:31,4478060432359830,震惊！！ 开天辟地之作， #苹果# 慌了， #雷军# 傻眼了，张老板坐不住了， #黄章# 也...,140,"{'id': 1967280501, 'screen_name': '科技小天', 'pro...",科技小天,0,私信看到都会回！感谢关注 ！！爱你们！！！,IwKHV9TTM
1,2020-02-28 20:18:31,4477057352854267,库克的苹果仍创新。 #苹果# #乔布斯# DannyData小丹尼的微博视频,55,"{'id': 2679375953, 'screen_name': 'DannyData小丹...",DannyData小丹尼,0,dannydata.com,IwkC3bYwz
2,2020-03-02 12:18:31,4478235738328329,#苹果# 年度股东大会召开，库克称疫情仍是挑战，要保持警惕！ 科技君的眼镜的微博视频,77,"{'id': 6086153006, 'screen_name': '科技君的眼镜', 'p...",科技君的眼镜,0,科学实验视频,IwPgFyWzT
3,2020-03-02 05:18:31,4478125188450007,再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...,583,"{'id': 7258446663, 'screen_name': '互联网八哥', 'pr...",互联网八哥,0,每日一扒，看不一样的互联网,IwMomzser
4,2020-03-02 01:18:31,4478064711058365,近日，苹果在日本发布了全新的动画广告视频，在各种动漫场景中展示了MacBook和AirPod...,248,"{'id': 7382535180, 'screen_name': '潮玩生活_张大喵', ...",潮玩生活_张大喵,-1,美妆、球鞋、数码、潮流好物这里都有～我是《潮玩生活》小编--张大喵。,IwKOP4rkp

In [44]:
appleen_df_filtered=appleen_df.drop(columns=["verified","source","longText"])
appleen_df_filtered.head()

,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
0.0,2020-03-01 03:42:50,4477738171840551,想找星空图但是没找到称心的？ 那就自己画吧~ 用Procreate可以三秒做一张！ 【工具】...,359,"{'id': 1774015623, 'screen_name': '嘉文钱', 'prof...",嘉文钱,0,PPT设计师，平面设计师，业余插画师，可以接稿,IwCk97IOj
1.0,2020-03-01 23:15:50,4478048000469140,【日本 Apple 全新 MacBook 广告集结著名动画场景】早前 Apple 日本推出全...,302,"{'id': 2067301197, 'screen_name': 'HYPEBEAST時尚...",HYPEBEAST時尚生活雜誌,3,HYPEBEAST 官方微博。 微信: hypebeastchina， 网站：http://...,IwKnS1Y2M
2.0,2020-03-01 21:42:50,4478024323998938,【来看看动画中的“水果电脑”】Apple Japan于近日公开了一支全新的广告，其中Appl...,308,"{'id': 1998412373, 'screen_name': '机核网', 'prof...",机核网,2,不止是游戏,IwJLGgMj0
3.0,2020-03-01 23:31:50,4478052039974125,我一直不敢讲 虽然我坚持用Apple Music白嫖bts歌两年多了 但是我人脸依然只认识n...,215,"{'id': 5855864588, 'screen_name': 'IsKayo', 'p...",IsKayo,-1,总有一个终点，花开满树是人间💮,IwKunFQIZ
4.0,2020-03-01 23:30:50,4478051947881706,#iPhone样机# 设计君每日欣赏超话 多角度苹果iPhone Xs手机样机Apple X...,98,"{'id': 3243464264, 'screen_name': 'UI设计君', 'pr...",UI设计君,0,NaN,IwKuex4oi

In [50]:
combined_df=pd.concat([applecn_filtered,appleen_df_filtered], sort = False)
combined_df =combined_df.reset_index()
combined_df = combined_df.drop(columns="index")
combined_df.head()

,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
0,2020-03-02 00:18:31,4478060432359830,震惊！！ 开天辟地之作， #苹果# 慌了， #雷军# 傻眼了，张老板坐不住了， #黄章# 也...,140,"{'id': 1967280501, 'screen_name': '科技小天', 'pro...",科技小天,0,私信看到都会回！感谢关注 ！！爱你们！！！,IwKHV9TTM
1,2020-02-28 20:18:31,4477057352854267,库克的苹果仍创新。 #苹果# #乔布斯# DannyData小丹尼的微博视频,55,"{'id': 2679375953, 'screen_name': 'DannyData小丹...",DannyData小丹尼,0,dannydata.com,IwkC3bYwz
2,2020-03-02 12:18:31,4478235738328329,#苹果# 年度股东大会召开，库克称疫情仍是挑战，要保持警惕！ 科技君的眼镜的微博视频,77,"{'id': 6086153006, 'screen_name': '科技君的眼镜', 'p...",科技君的眼镜,0,科学实验视频,IwPgFyWzT
3,2020-03-02 05:18:31,4478125188450007,再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...,583,"{'id': 7258446663, 'screen_name': '互联网八哥', 'pr...",互联网八哥,0,每日一扒，看不一样的互联网,IwMomzser
4,2020-03-02 01:18:31,4478064711058365,近日，苹果在日本发布了全新的动画广告视频，在各种动漫场景中展示了MacBook和AirPod...,248,"{'id': 7382535180, 'screen_name': '潮玩生活_张大喵', ...",潮玩生活_张大喵,-1,美妆、球鞋、数码、潮流好物这里都有～我是《潮玩生活》小编--张大喵。,IwKOP4rkp

In [52]:
comb_df =combined_df.drop_duplicates() #734 rows after dropping duplicates

In [84]:
comb_df.query("textLength == 'textLength'")

,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
559,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
581,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,longText
612,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,NaN

In [86]:
comb_df_cleaned=comb_df.drop([559,581,612])

In [96]:
comb_df_cleaned=comb_df_cleaned.fillna(0)

In [97]:
comb_df_cleaned['textLength'].unique()

array([140, 55, 77, 583, 248, 101, 447, 92, 107, 182, 63, 230, 139, 594,
       191, 417, 93, 61, 24, 115, 74, 438, 532, 196, 123, 530, 195, 156,
       159, 71, 48, 98, 23, 311, 237, 88, 495, 39, 143, 894, 89, 187, 119,
       96, 80, 255, 54, 544, 170, 712, 516, 82, 102, 448, 94, 431, 177,
       257, 30, 355, 675, 1164, 58, 596, 354, 786, 137, 634, 711, 2066,
       611, 676, 173, 116, 186, 747, 205, 216, 1450, 35, 238, 360, 429,
       411, 1411, 183, 1478, 57, 287, 432, 260, 121, 266, 110, 118, 316,
       64, 502, 331, 83, 2182, 700, 79, 324, 163, 1563, 202, 402, 246,
       1006, 277, 52, 423, 217, 245, 104, 162, 134, 298, 270, 477, 160,
       339, 99, 269, 190, 261, 460, 103, 114, 111, 291, 97, 108, 85, 87,
       213, 338, 327, 42, 171, 178, 456, 207, 36, 1355, 120, 124, 254,
       256, 210, 231, 68, 112, 224, 73, 244, 174, 59, 12, 66, 47, 720, 62,
       129, 164, 1036, 1429, 305, 86, 81, 310, 75, 176, 289, 405, 458, 46,
       135, 329, 211, 240, 290, 629, 223, 128, 72, 194, 91, 446, 303, 384,
       538, 1531, 161, 168, 251, 421, 154, 169, 215, 209, 346, 149, 76,
       424, 273, 301, 539, 95, 105, 312, 823, 563, 884, 778, 33, 584, 113,
       117, 570, 199, 142, 365, 397, 548, 404, 109, 281, 1237, 239, 78,
       624, 457, 26, 328, 400, 50, 279, 320, 428, 167, 373, 65, 436, 153,
       390, 67, 175, 481, 233, 392, 471, 344, 343, 569, 34, 243, 427, 496,
       258, 418, 206, 367, 1262, 574, 478, 523, 192, 189, 399, 361, 963,
       141, 181, 100, 398, 536, 247, 198, 434, 474, 127, 227, 1167, 1863,
       470, 578, 1140, 412, 444, 17, 933, 1236, 307, 264, 60, 714, 274,
       136, 347, 294, 314, 184, '359', '302', '308', '215', '98', '160',
       '91', '167', '183', '90', '200', '35', '48', '142', '231', '238',
       '290', '105', '282', '56', '114', '37', '97', '53', '49', '143',
       '73', '47', '9', '77', '96', '107', '268', '51', '65', '111', '78',
       '104', '54', '121', '39', '67', '187', '61', '697', '411', '263',
       '26', '63', '79', '100', '255', '145', '124', '72', '108', '321',
       '125', '207', '281', '86', '156', '299', '76', '110', '180', '43',
       '162', '158', '234', '113', '60', '455', '18', '260', '22', '206',
       '75', '210', '269', '102', '85', '34', '448', '129', '99', '123',
       '1470', '30', '128', '146', '229', '122', '139', '272', '168',
       '305', '57', '59', 0, '159', '93', '191', '181', '140', '172',
       '87', '202', '64', '161', '58', '69', '286', '213', '8'],
      dtype=object)

In [101]:
comb_df_cleaned['textLength']=comb_df_cleaned['textLength'].astype(int)

In [100]:
sum(comb_df_cleaned['textLength'].astype(int))

178902

In [107]:
comb_df_cleaned['verified_type'].astype(int)

0        0
1        0
2        0
3        0
4       -1
      ...
744    200
745     -1
746     -1
747     -1
748     -1
Name: verified_type, Length: 731, dtype: int32

In [109]:
comb_df_cleaned['verified_type'] = comb_df_cleaned['verified_type'].astype(int)

In [113]:
#669 rows
comb_person = comb_df_cleaned.query("verified_type == -1 or verified_type == 0 or verified_type == 200 or verified_type == 220")

In [114]:
comb_person.head()

,created_at,member_id,text,textLength,user,screen_name,verified_type,user_description,bid
0,2020-03-02 00:18:31,4478060432359830,震惊！！ 开天辟地之作， #苹果# 慌了， #雷军# 傻眼了，张老板坐不住了， #黄章# 也...,140,"{'id': 1967280501, 'screen_name': '科技小天', 'pro...",科技小天,0,私信看到都会回！感谢关注 ！！爱你们！！！,IwKHV9TTM
1,2020-02-28 20:18:31,4477057352854267,库克的苹果仍创新。 #苹果# #乔布斯# DannyData小丹尼的微博视频,55,"{'id': 2679375953, 'screen_name': 'DannyData小丹...",DannyData小丹尼,0,dannydata.com,IwkC3bYwz
2,2020-03-02 12:18:31,4478235738328329,#苹果# 年度股东大会召开，库克称疫情仍是挑战，要保持警惕！ 科技君的眼镜的微博视频,77,"{'id': 6086153006, 'screen_name': '科技君的眼镜', 'p...",科技君的眼镜,0,科学实验视频,IwPgFyWzT
3,2020-03-02 05:18:31,4478125188450007,再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...,583,"{'id': 7258446663, 'screen_name': '互联网八哥', 'pr...",互联网八哥,0,每日一扒，看不一样的互联网,IwMomzser
4,2020-03-02 01:18:31,4478064711058365,近日，苹果在日本发布了全新的动画广告视频，在各种动漫场景中展示了MacBook和AirPod...,248,"{'id': 7382535180, 'screen_name': '潮玩生活_张大喵', ...",潮玩生活_张大喵,-1,美妆、球鞋、数码、潮流好物这里都有～我是《潮玩生活》小编--张大喵。,IwKOP4rkp

In [115]:
sum(comb_person['textLength'])

158177

In [116]:
comb_person['text']

0      震惊！！ 开天辟地之作， #苹果# 慌了， #雷军# 傻眼了，张老板坐不住了， #黄章# 也...
1                 库克的苹果仍创新。 #苹果# #乔布斯# DannyData小丹尼的微博视频
2             #苹果# 年度股东大会召开，库克称疫情仍是挑战，要保持警惕！ 科技君的眼镜的微博视频
3      再次折戟！苹果突围失败！针对苹果成立的统一充电口法案还未实施，欧盟又再一次掀起对智能手机的改...
4      近日，苹果在日本发布了全新的动画广告视频，在各种动漫场景中展示了MacBook和AirPod...
                             ...
744      想有个apple watch上的siri当我的三月好朋友 陪我道晚安 在线抽一名幸运儿送我一个
745    宅在家里能干啥系列， 第7天， 插一瓶鲜花，享受大自然的美好 @李五点zka @大元huah...
746                                             Apple is
747           【Day16】 Apple pencil摔了，心疼 。 10块一支的笔果然很好用 。
748          …几乎要把apple pencil捏成两段的程度。 … 说什么屁话啦，我手劲可没那么大
Name: text, Length: 669, dtype: object

In [146]:
comb_nobid =comb_person[['created_at','member_id','screen_name','text','textLength','verified_type','user_description','user']] #669 rows

In [148]:
len(comb_nobid['text'].unique())  #only 568 rows after removing duplicate texts

568

In [152]:
unique_ind=comb_nobid['text'].drop_duplicates().index

In [165]:
unique_Apple_comments=comb_nobid.loc[unique_ind]

In [171]:
unique_Apple_comments.loc[727]
unique_Apple_comments=unique_Apple_comments.drop(727)

In [173]:
unique_Apple_comments['created_at']=unique_Apple_comments['created_at'].str.extract("(\d{4}-\d{2}-\d{2})")

In [157]:
sum(unique_Apple_comments['textLength']) # after all cleaning still has 13,5000 words

135109

In [174]:
unique_Apple_comments.to_csv("Apple_comb_personsonly.csv", index=True, encoding='gb18030',header=True)

In [6]:
Amazon_df = pd.read_csv(r"C:\Users\gen80\OneDrive\Documents\MDSlectures\COLX_523_advanced_corp_ling\COLX523_SH_VT_AL\codes\tidied_csv\5fields\Amazon_weibo_tidied2.csv",header=None)

In [7]:
Amazon_df.head()

,0,1,2,3,4
0,"February 25, 2020",4.480000e+15,# 自闭日记 1. 我宝贵的休息时间在干嘛呢， 和amazon吵吵， 和hsbc吵吵， 和h...,zh,"{'id': 1762825882, 'screen_name': '一木成零', 'pro..."
1,"February 6, 2020",4.470000e+15,#197万只假飘安口罩流入湖南市场# 加拿大amazon买不着，女友在美国amazon买的，...,zh,"{'id': 1364250233, 'screen_name': '萝卜泡泡有一只胖胖的咖..."
2,"February 2, 2020",4.470000e+15,#amazon 有些地方，一辈子总要来一次，当然不见得还要再来，我说的就是亚马逊雨林。 亚马...,zh,"{'id': 1694601031, 'screen_name': '魔都莎曼萨', 'pr..."
3,"February 29, 2020",4.480000e+15,#Amazon# 这部最新自制原创 #科幻# 美剧 #TALES FROM THE LOOP...,zh,"{'id': 1914675127, 'screen_name': 'Qrious乔治', ..."
4,"February 2, 2020",4.470000e+15,#Amazon亚马逊世界总部# (来自 @安迪樊AndyFan 的一直播 下载地址 网页链接...,zh,"{'id': 1400228952, 'screen_name': '方冰老师', 'pro..."

In [17]:
Amazon_df[2]=Amazon_df[2].astype("str")

In [22]:
sum(Amazon_df[2].apply(lambda x:len(x)))

78813

In [21]:
Amazon_df[2][0]

'# 自闭日记 1. 我宝贵的休息时间在干嘛呢， 和amazon吵吵， 和hsbc吵吵， 和hungrypanda吵吵。 我的货呢 我的钱呢 我的饭呢。 2. 我的货大概是被人拿走了。 也是，香喷喷的pasta jelly谁不爱呢。 只不过是买来毒老鼠的。 3. 和只会踢皮球的access管理员磨了一个礼拜的permission，大大大老板一句怼 ... 全文'